name: golang-pipeline
on:
  push:
    tags:
      - 'v*'
jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: go vet ./...

  publish:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    needs: tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ibesprozvannykh/todo-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}